language: php

php : '5.6'

before_script:
    - composer install
    - php -d always_populate_raw_post_data=-1 -S localhost:1349 -t demo >/dev/null 2>&1 &
    
script: 
    - phpunit -c build/phpunit.xml --coverage-clover=coverage.xml tests/
    - ./bin/behat

after_success:
    - bash <(curl -s https://codecov.io/bash)
