language: php

php : '5.6'

before_script:
    - php -S localhost:1349 -t demo &
    - sleep 3
    
script: phpunit -c build/phpunit.xml --coverage-clover=coverage.xml tests/

after_success:
    - bash <(curl -s https://codecov.io/bash)
